### ISSUE TITLE
Remove Angular FR FR FR FR now! 💀💀💀💀💀💀💀

### ISSUE THREAD

**Issue by scarletquasar** [paulo-e/imageboard#2]
## Summary

- Remove angular from the projekt
- Remove angular
- Delet angular
- No angular only react vue react native backbonejs no angular allowed

**Comment by voidcoefficient** [comment]
Hi, [CUSTOMER NAME]!

Thanks for your contribution. Your input was relayed to the team lead, that is discussing with the engineering manager if we have enough resources to make this leap forward. The project owner is discussing with the stakeholders if this is the shape we want the product to look like. The team leader is drawing the diagram of how a rewrite will look like. The senior developers are secretly complaining about having to do re-work and how this is going to make them lose the *new promotion to team leader* people where hoping for. Mid level developers are excited to finally stop fixing bugs. Junior developers are looking for new positions. The intern probably doesn't know about this. The data scientist is busy with their PhD. The designer is locked in a cave studying the new design system. The frontend team has 7 new libraries to learn. The backend team finished yet another API. Our DBA is missing. The engineering manager's manager is asking for reports about this very ticket. JIRA is down. Teams seems to be slow today. We may have to hire for this. We have OKRs to complete. We are in the holiday season. I don't know what will happen. I'm afraid.

Yours truly,
[EMPLOYEE NAME].

**DON'T FORGET TO CHANGE THE NAMES**!
**YOU WILL GET FIRED**!

**Comment by voidcoefficient** [comment]
Hey, @victoriaquasar.

Sorry for the latest reply. We do not use templates to answer customers. The person that replied before was fired. They were supposed to have been fired before but the person responsible for firing others was fired. I will forward this directly to our team leader. Email them as much as you want to follow progress on this issue.

@minsk-dev.
